"""Phase 105: tests for the shared dependency-admission parsing helpers."""
from __future__ import annotations

import textwrap
from datetime import datetime, timezone

import pytest

from qor.scripts import _dep_admit_common as common


def test_parse_lockfile_entries_extracts_name_version_hashes():
    """Parse pip-compile --generate-hashes format; assert dataclass fields match observed input."""
    text = textwrap.dedent("""\
        #
        # autogenerated by pip-compile
        #
        build==1.5.0 \\
            --hash=sha256:13f3eecb844759ab66efec90ca17639bbf14dc06cb2fdf37a9010322d9c50a6f \\
            --hash=sha256:302c22c3ba2a0fd5f3911918651341ebb3896176cbdec15bd421f80b1afc7647
            # via -r requirements-release.in
        packaging==26.2 \\
            --hash=sha256:5fc45236b9446107ff2415ce77c807cee2862cb6fac22b8a73826d0693b0980e \\
            --hash=sha256:ff452ff5a3e828ce110190feff1178bb1f2ea2281fa2075aadb987c2fb221661
            # via build
        """)

    entries = common.parse_lockfile_entries(text)
    by_name = {e.name: e for e in entries}

    assert "build" in by_name
    assert by_name["build"].version == "1.5.0"
    assert len(by_name["build"].hashes) == 2
    assert all(h.startswith("sha256:") for h in by_name["build"].hashes)
    assert len(by_name["build"].hashes[0]) == 64 + len("sha256:")

    assert "packaging" in by_name
    assert by_name["packaging"].version == "26.2"
    assert len(by_name["packaging"].hashes) == 2


def test_parse_lockfile_entries_rejects_malformed_input():
    """Malformed input -> named exception, not silent corruption."""
    malformed = "build==1.5.0 --hash=NOT_SHA256_PREFIX:abc\n"
    with pytest.raises(common.LockfileParseError):
        common.parse_lockfile_entries(malformed)


def test_diff_lockfile_returns_new_and_bumped_entries():
    """Given two lockfile sets, returns new + version-bumped entries with correct old_version."""
    base = [
        common.LockfileEntry(name="packaging", version="25.0", hashes=("sha256:" + "a" * 64,)),
        common.LockfileEntry(name="oldonly", version="1.0", hashes=()),
    ]
    current = [
        common.LockfileEntry(name="packaging", version="26.2", hashes=("sha256:" + "b" * 64,)),
        common.LockfileEntry(name="newadd", version="2.0", hashes=()),
    ]

    bumps = common.diff_lockfile_against_base(current, base)
    by_name = {b.name: b for b in bumps}

    # Bumped: packaging 25.0 -> 26.2
    assert "packaging" in by_name
    assert by_name["packaging"].old_version == "25.0"
    assert by_name["packaging"].new_version == "26.2"
    # New: newadd None -> 2.0
    assert "newadd" in by_name
    assert by_name["newadd"].old_version is None
    assert by_name["newadd"].new_version == "2.0"
    # Removed entries (oldonly) are NOT in bumps; removal is not an admission event.
    assert "oldonly" not in by_name


def test_parse_override_entries_extracts_package_version_justification():
    """Walk a synthetic META_LEDGER fragment; assert overrides parsed with all required fields."""
    ledger_fragment = textwrap.dedent("""\
        ### Entry #999: IMPLEMENTATION -- some phase

        **Timestamp**: 2026-05-20T12:00:00Z

        **Scope**: example.

        **Dependency admission override**: openssl-py@3.1.4; upload_age_days=2; justification=CVE-2026-1234 critical patch coordinated with upstream maintainers.

        ---

        ### Entry #1000: IMPLEMENTATION -- another

        **Timestamp**: 2026-05-22T08:00:00Z

        **Dependency admission override**: requests@2.32.0; upload_age_days=7; justification=upstream maintainer-coordinated security release.

        ---
        """)

    overrides = common.parse_override_entries(ledger_fragment)
    assert len(overrides) == 2

    by_pkg = {o.package: o for o in overrides}
    assert "openssl-py" in by_pkg
    assert by_pkg["openssl-py"].version == "3.1.4"
    assert by_pkg["openssl-py"].upload_age_days == 2
    assert "CVE-2026-1234" in by_pkg["openssl-py"].justification
    assert by_pkg["openssl-py"].entry_ts == datetime(2026, 5, 20, 12, 0, 0, tzinfo=timezone.utc)

    assert "requests" in by_pkg
    assert by_pkg["requests"].version == "2.32.0"
    assert by_pkg["requests"].upload_age_days == 7
    assert by_pkg["requests"].entry_ts == datetime(2026, 5, 22, 8, 0, 0, tzinfo=timezone.utc)


# --- Phase 106: parse_pyproject_exact_pins ------------------------------------


def test_parse_pyproject_exact_pins_extracts_pinned_entries():
    """Exact-pin (`==X.Y.Z`) entries returned; range / unbounded forms skipped."""
    text = textwrap.dedent("""\
        [project]
        name = "demo"
        version = "0.1.0"
        dependencies = [
            "pinned-pkg==1.2.3",
            "ranged-pkg>=4",
            "unbounded-pkg",
            "another-pin==9.9.9",
        ]
        """)
    pins = common.parse_pyproject_exact_pins(text)
    by_name = {p.name: p for p in pins}

    assert "pinned-pkg" in by_name
    assert by_name["pinned-pkg"].version == "1.2.3"
    assert by_name["pinned-pkg"].hashes == ()
    assert "another-pin" in by_name
    assert by_name["another-pin"].version == "9.9.9"
    # Range / unbounded skipped
    assert "ranged-pkg" not in by_name
    assert "unbounded-pkg" not in by_name


def test_parse_pyproject_exact_pins_handles_optional_dependencies():
    """`[project.optional-dependencies]` groups are also scanned."""
    text = textwrap.dedent("""\
        [project]
        name = "demo"
        version = "0.1.0"
        dependencies = ["base-pin==1.0.0"]

        [project.optional-dependencies]
        dev = ["dev-pin==2.0.0", "dev-range>=3"]
        test = ["test-pin==4.5.6"]
        """)
    pins = common.parse_pyproject_exact_pins(text)
    by_name = {p.name: p for p in pins}

    assert "base-pin" in by_name
    assert "dev-pin" in by_name and by_name["dev-pin"].version == "2.0.0"
    assert "test-pin" in by_name and by_name["test-pin"].version == "4.5.6"
    assert "dev-range" not in by_name


def test_parse_pyproject_exact_pins_returns_empty_for_no_exact_pins():
    """qor-logic's own pyproject (range-only deps) yields empty list."""
    text = textwrap.dedent("""\
        [project]
        name = "qor-logic"
        version = "0.74.0"
        dependencies = ["jsonschema>=4", "PyYAML>=6"]

        [project.optional-dependencies]
        dev = ["pytest>=8"]
        """)
    pins = common.parse_pyproject_exact_pins(text)
    assert pins == []


# --- Phase 107 D-107.3: range-pin lower-bound coverage -----------------------


def test_parse_pyproject_range_pins_extracts_lower_bound():
    """`>=X.Y.Z` and `~=X.Y.Z` return lower-bound version; `<` / unbounded skipped."""
    text = textwrap.dedent("""\
        [project]
        name = "demo"
        version = "0.1.0"
        dependencies = [
            "ge-pkg>=1.2.3",
            "compat-pkg~=4.5.6",
            "upper-only<2.0",
            "unbounded",
            "exact==9.9.9",
        ]
        """)
    pins = common.parse_pyproject_range_pins(text)
    by_name = {p.name: p for p in pins}

    assert "ge-pkg" in by_name
    assert by_name["ge-pkg"].version == "1.2.3"
    assert "compat-pkg" in by_name
    assert by_name["compat-pkg"].version == "4.5.6"
    # < only: no lower bound -> skipped
    assert "upper-only" not in by_name
    # unbounded -> skipped
    assert "unbounded" not in by_name
    # exact pins handled by parse_pyproject_exact_pins; not this parser's job
    assert "exact" not in by_name


def test_parse_pyproject_range_pins_handles_combined_specifiers():
    """`>=X.Y,<Z.0` returns the lower bound only (the `>=` part)."""
    text = textwrap.dedent("""\
        [project]
        name = "demo"
        version = "0.1.0"
        dependencies = [
            "combined>=1.0,<2.0",
            "tilde~=3.4",
        ]
        """)
    pins = common.parse_pyproject_range_pins(text)
    by_name = {p.name: p for p in pins}

    assert "combined" in by_name
    assert by_name["combined"].version == "1.0"
    assert "tilde" in by_name
    assert by_name["tilde"].version == "3.4"
