"""Phase 137 guard; Phase 164 retirement of the header-currency tests.

The two live header-currency tests (header phase within one of the latest
seal; snapshot date parseable) were retired in Phase 164 (generate-not-assert,
research entry #378 rec 2): the header is now GENERATED by
`qor.scripts.seal_artifacts` at substantiate Step 6, and currency is enforced
by Step 6.5 `seal_artifacts --check` (ABORT) + the CI `seal-artifacts
currency` step, where repo state is stable. The header semantics themselves
are behaviorally tested in tests/test_seal_artifacts.py.
"""
from __future__ import annotations


def test_existing_phase_coverage_helpers_still_resolve() -> None:
    # Guards that the historical per-phase sections remain (no regression of the
    # existing coverage contract from this resync).
    from test_system_state_phase_coverage import (
        _phases_in_system_state,
        _sealed_phases_from_ledger,
    )
    in_state = _phases_in_system_state()
    assert 57 in in_state, "historical Phase 57 section disappeared from SYSTEM_STATE"
    assert not (_sealed_phases_from_ledger() - in_state), "feature-substantiated coverage regressed"
