# Plan: Add /qor-harden as a reusable implementation-quality capability (GH #388)

**change_class**: feature

**doc_tier**: standard

**originating_remediation**: GH #388

**terms_introduced**:
- term: Implementation-Quality Sweep
  home: qor/references/implementation-quality-sweep.md

**boundaries**:
- limitations: the sweep protocol is a reasoning contract, not an executable scanner; enforcement of its truthfulness lives in the contract tests and the existing substantiate gates, not in a new runtime.
- non_goals: does not create a second code-quality doctrine (an earlier draft doctrine-implementation-quality.md was deliberately removed as duplicative of qor/references/doctrine-code-quality.md); does not turn lifecycle skills' quality checks into nested /qor-harden lifecycle invocations.
- exclusions: /qor-refactor modernization around the same taxonomy is a separate issue (GH #392), out of this plan's scope.

## Open Questions

None. GH #388's capability boundary questions were resolved during implementation and are encoded as authority-boundary rules in the skill.

## Locked Decisions

**LD-1: Single canonical quality doctrine.** The implementation-quality invariants (abstention-as-success, evidence precedence) live in the existing `qor/references/doctrine-code-quality.md`; the removed standalone doctrine is not reintroduced; the IQ dimension identifiers live only in the sweep reference and the skill. Verified: `ls qor/references/doctrine-implementation-quality.md` -> no such path on the branch head; `grep -n "Abstention is a successful outcome" qor/references/doctrine-code-quality.md` line 99 -> `## 14. Abstention is a successful outcome`.

**LD-2: Reusable sweep protocol.** `qor/references/implementation-quality-sweep.md` holds the canonical inspection protocol (nine IQ dimensions, scope modes, dispositions, lifecycle profiles) so `/qor-plan`, `/qor-audit`, `/qor-implement`, `/qor-debug`, `/qor-refactor`, `/qor-substantiate`, and `/qor-deep-audit` reuse the taxonomy by reference without invoking a nested `/qor-harden` ceremony. Verified: `grep -n "/qor-deep-audit" qor/references/implementation-quality-sweep.md` -> lifecycle profile row present.

**LD-3: Environment-neutral by contract, not vocabulary.** The skill declares itself agent-, model-, host-, repository-, language-, framework-, provider-, forge-, runtime-, and deployment-agnostic; carries no `model_compatibility` / `min_model_capability` frontmatter; forbids inferring AI authorship from implementation shape; and repository/context evidence takes precedence over generic heuristics. Verified: `grep -n "deployment-agnostic" qor/skills/sdlc/qor-harden/SKILL.md` -> declaration present.

**LD-4: Registry/help/discovery currency.** The skill is registered in `docs/SKILL_REGISTRY.md`, `qor/skills/meta/qor-help/SKILL.md`, `qor/gates/delegation-table.md`, the README catalog + Skills badge (30 -> 31), and the compiled `qor/dist/**` variants regenerated by the repository's dist compiler. Verified: `grep -n "qor-harden" docs/SKILL_REGISTRY.md README.md qor/gates/delegation-table.md` -> rows present at each surface.

## Phase 1: Standalone skill + canonical taxonomy (test-first)

### Affected Files

- `tests/test_qor_harden.py` - NEW. Nine behavior-contract tests (existence, environment agnosticism, scope modes + dispositions, canonical taxonomy without language-specific rules, non-mutating review / scope-bound repair, abstention as success, lifecycle profile boundaries, authority boundaries, truthful three-state ship verdict).
- `qor/skills/sdlc/qor-harden/SKILL.md` - NEW. Standalone skill: scopes `focused` / `changeset` / `component` / `comprehensive`; dispositions `review` / `repair`; nine IQ dimensions; authority boundaries with `/qor-debug`, `/qor-refactor`, `/qor-plan`, `/qor-remediate`, `/qor-substantiate`.
- `qor/references/implementation-quality-sweep.md` - NEW. Canonical reusable inspection protocol.
- `qor/references/doctrine-code-quality.md` - unified implementation-quality invariants into the canonical doctrine (abstention-as-success, evidence precedence).

### Unit Tests

- `tests/test_qor_harden.py` - asserts the delivered contracts above; notably the agnosticism test asserts the declared contract text and the absence of model-pinning frontmatter rather than scanning for banned vocabulary alone. Iteration 2 adds `test_discovery_surfaces_enumerate_every_canonical_dimension`: it derives the canonical dimension set from the sweep's own `### IQ-*:` headings and fails when the SKILL frontmatter description, the Step 3 list, or the qor-help catalog row omits any dimension (the iteration-1 independent audit found IQ-CONTEXT missing from both selection surfaces).

## Phase 2: Discovery wiring + variant sync

### Affected Files

- `docs/SKILL_REGISTRY.md` - register qor-harden row.
- `qor/skills/meta/qor-help/SKILL.md` - catalog entry + routing guidance.
- `qor/gates/delegation-table.md` - delegation rows for harden handoffs.
- `README.md` - catalog row + Skills badge 30 -> 31.
- `qor/references/glossary.md` - register the Implementation-Quality Sweep term (iteration 2; the iteration-1 independent audit found the declared term unregistered while the gate artifact's non-canonical `terms_introduced` key made the glossary check inspect nothing).
- `qor/dist/manifest.json`, `qor/dist/variants/**` - regenerated compiled variants (claude, cline, codex, cursor, gemini, kilo-code).

### Unit Tests

- existing `tests/test_qor_onboard_skill.py::test_registry_and_badge_updated` - README badge count equals registry row count (31).
- existing variant-drift checks (`qor/scripts/check_variant_drift.py` surface) - compiled variants match source.

## Definition of Done

### Deliverable: /qor-harden capability

- **D1**: A reusable, environment-neutral implementation-quality review/repair capability with a canonical nine-dimension taxonomy, per GH #388.
- **D2**: `qor/skills/sdlc/qor-harden/SKILL.md` + `qor/references/implementation-quality-sweep.md` + unified `qor/references/doctrine-code-quality.md`, wired into registry/help/delegation/README/dist.
- **D3**: Ledger entries (plan citation, tribunal verdict, implementation record, session seal) on this branch; PR #391 body cites this plan and the Merkle seal.
- **D4**: `tests/test_qor_harden.py` (9 tests) green; full suite green (3046 passed locally, run twice for determinism at seal time).

## CI Commands

- `python -m pytest tests/test_qor_harden.py -q`
- `python -m qor.scripts.publication_boundary_lint`
- `python -m pytest tests/ -q`

**ci_commands**:
- `python -m pytest tests/test_qor_harden.py -q`
- `python -m qor.scripts.publication_boundary_lint`
- `python -m pytest tests/ -q`

## Governance note

This plan and its audit/implement/substantiate artifacts were authored after the skill, doctrine unification, wiring, and tests had already been written and verified green on `phase/244-qor-harden` (the work arrived through a relay handoff that completed implementation before this repository's citation gate was consulted). Per the Phase 235 precedent, the governance ceremony is completed honestly and in full rather than papered over: every fact recorded in the gate artifacts and this plan file is a true, independently-verifiable description of work already done and already tested. No test result, hash, or verdict is fabricated to satisfy the gate; the gate is satisfied because the artifacts it demands are real.
